#Browser SELECTION
browser = chrome
#URL SELECTION
url= https://www.demoblaze.com/
#APPLICATION LOGIN DETAIL
username= Amitesh01
password= Amitesh098
#Billing Detail
name = Amitesh Singh
country = India
city = Chennai
creditcard = 3456342678987654
month = march
year = 2026